# Generated by Django 4.2.3 on 2023-08-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_category_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
    ]
